### PR TITLE
Add an alter hook for modifying component markup

### PR DESCRIPTION
**Pull request by hawkeyetwolf**

### CODE REVIEW

**Review by soniktrooth — APPROVED** [review]
I left comments re: render arrays on the HSA issue. This would apply here

**Comment by soniktrooth** [comment]
https://github.com/Exygy/HSA-Drupal/pull/76

**Comment by hawkeyetwolf** [comment]
Approved by @soniktrooth, so I'ma merge this puppy!

**Review by RobLoach — COMMENTED** [review]
:+1:

**Pull request merged**
